
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue May 30 05:03:29 BRT 2017
//----------------------------------------------------

package analisador_lexico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SAIDA = 20;
  public static final int LINHA = 2;
  public static final int ELSE = 8;
  public static final int OP_ARITMETICO = 3;
  public static final int OP_ATRIBUICAO = 6;
  public static final int OP_RELACIONAL = 5;
  public static final int ERROR = 15;
  public static final int IF = 7;
  public static final int ID = 11;
  public static final int SEPARADOR = 9;
  public static final int ABRE_PARENTESE = 12;
  public static final int FLOAT = 25;
  public static final int EOF = 0;
  public static final int TIPO_VARIAVEL = 21;
  public static final int NUMERO = 24;
  public static final int ESPECIAL = 18;
  public static final int PALAVRARESERVADA = 17;
  public static final int error = 1;
  public static final int ENTRADA = 19;
  public static final int ABRE_CHAVE = 14;
  public static final int OP_LOGICO = 4;
  public static final int FOR = 10;
  public static final int FECHA_PARENTESE = 13;
  public static final int PONTOEVIRGULA = 16;
  public static final int FIM = 23;
  public static final int INICIO = 22;
}

