package analisador_lexico;

public enum Token {
  /* Tokens do arquivo Lexer.flex*/
    LINHA, OP_ARITMETICO, OP_LOGICO, OP_RELACIONAL, OP_ATRIBUICAO, OP_CONDICIONAL, OP_BOOLEANO,
    SEPARADOR, ESPECIAL, COMENTARIO, OP_REPETICAO, PALAVRARESERVADA, LETRA, ID, NUMERO, FLOAT,
    ERROR, PALAVRA,
    
  /* Tokens do arquivo Lexer1.flex*/
    FOR, IF,WHILE, ABRE_PARENTESE, FECHA_PARETENSE, ABRE_CHAVE, PONTOEVIRGULA, ENTRADA, SAIDA, TIPO_VARIAVEL
    

}
